apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-api-joao
  title: Sample Service API Joao
  description: >
    A service for testing Backstage functionality. Configured for
    GitHub Actions and

    Sentry.
  labels:
    tier: "3"
  links:
    - url: https://www.notion.so/roadie/Sample-Service-e067465e56a14ae9b0507f8559f6aa26
      title: Datadog
      icon: dashboard
  tags:
    - test
    - js
    - demo
  annotations:
    github.com/project-slug: JoaoMartins51/sample-service
    datadoghq.com/tag-name: sample-service
    datadoghq.com/slo_tag: service:tutorial-slo-api
    datadoghq.com/monitor_tags: sample-service
spec:
  type: service
  owner: sample-team
  lifecycle: production
  system: sample-system
  providesApis:
    - sample-service
  dependsOn:
    - Component:sample-service-2
    - Resource:sample-s3-bucket
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-service-trigger
  description: Push jobs onto a globally available shared queue.
spec:
  type: library
  lifecycle: production
  owner: roadie
